app:
  auth:
    token: test
  exchange:
    feedbackMailAddress: example@example.com
  webuntis:
    enabled: false
  jobmarket:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/othapp
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
  thymeleaf:
    cache: false
  resources:
    chain:
      html-application-cache: false
      enabled: true
      strategy:
        content:
          enabled: true
      cache: false
