create table BUILDING_FACULTIES
(
    BUILDING INT not null,
    FACULTY  INT not null,
    constraint PK_BUILDING_FACULTIES
        primary key (BUILDING, FACULTY),
    constraint FK_BFACULTIES_BUILDING
        foreign key (BUILDING) references BUILDING (ID),
    constraint FK_BFACULTIES_FACULTY
        foreign key (FACULTY) references FACULTY (ID)
);

INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (1, 6);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (2, 6);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (3, 6);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (4, 1);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (5, 1);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (6, 1);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (6, 3);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (7, 1);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (7, 3);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (7, 5);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (8, 5);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (8, 6);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (9, 3);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (10, 8);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (11, 2);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (12, 4);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (12, 5);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (12, 7);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (14, 5);
INSERT INTO BUILDING_FACULTIES (BUILDING, FACULTY) VALUES (14, 8);